services:
  - type: web
    name: django-service
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn blog_project.wsgi:application --bind 0.0.0.0:$PORT
